### ISSUE TITLE
Game info screen

### ISSUE THREAD

**Issue by ivan-ristovic** [matf-pp/2023_Pipaluk#2]
The game looks awesome and simple enough to understand, but I think an info/help screen (or a tutorial level) that explains the game concepts/mechanics and enemy types would be helpful regardless. What do you think?

**Comment by daniilgrbic** [comment]
We were inspired by retro games during the planning phase, and it was a deliberate choice to leave exploration of the game mechanics to the players. 

The only action the player can do is move by clicking around the screen, and we give a very precise indication (path highlighting) to encourage players to move around.  The description and visual style of the game clearly convey the goal is to find something (the exit),  and the player will know the exit once they see it.
